from .dispense_admin import DispenseAdmin
from .damage_admin import DamageAdmin
from .drug_admin import DrugAdmin
from .patient_admin import PatientAdmin
from .profile_admin import ProfileAdmin
from .protocol_admin import ProtocolAdmin
from .site_admin import SiteAdmin
from .stock_admin import StockAdmin
from .supplier_admin import SupplierAdmin
